# Generated by Django 2.2.3 on 2020-03-10 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='images',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
    ]
