# Generated by Django 2.2.3 on 2020-03-10 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0002_pokemon_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='images',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
